### ISSUE TITLE
Issues when importing LayerComponents (from Constructions)

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/energy-ade-citydb#4]
Hi, 

I think I have found another bug, similar to those already reported. I am using the Importer/Exporter and the energy-ADE-citydb updated and compiled as of today (27.4.2021).

I have created a sample data containing 2 constructions. Upon import, gml_id, name and description properties are not imported. The LayerComponent objects are assigned a (new) id generated upon import. All other objects are imported correctly.

Here the sample file. The data are compliant with the KIT profile.

[Sample_construction.zip](https://github.com/3dcitydb/energy-ade-citydb/files/6384906/Sample_construction.zip)

**Comment by clausnagel** [comment]
Thanks for your careful testing, @gioagu. Yes, was indeed a similar bug in the citygml4j parser module. Fixed here: https://github.com/citygml4j/energy-ade-citygml4j/commit/e9dea8aae98a546f330105fe9d6c34231f56ef61

**Comment by clausnagel** [comment]
fixed in version [1.2.1](https://github.com/3dcitydb/energy-ade-citydb/releases/tag/v1.2.1)
