### ISSUE TITLE
Left over, unused table (NG_TIMEVALUESPROPERTIES)?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/energy-ade-citydb#8]
Hi!

I am using the latest version of the citydb_energy_ade.

I found that table NG_TIMEVALUESPROPERTIES is actually redundant, possibly a leftover from past mapping rules.
As a matter of fact, its contents are repeated in table NG_TIMESERIES, and the current Importer/Exporter correctly saves data there.

So, I think it can be safely dropped from the install script.

BR

GA

**Comment by clausnagel** [comment]
Thanks @gioagu. The 3DCityDB mapping is automatically derived from the XML Schema of the [KIT EnergyADE 1.0 profile](https://github.com/citygml4j/energy-ade-citygml4j/blob/master/resources/ade-xjc/EnergyADE.xsd). The change would have to be made in this schema but the schema is not under our control.
