### ISSUE TITLE
Left over, unused table (NG_ENERGYDEM_TO_CITYOBJEC)?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/energy-ade-citydb#9]
Same issue as before.
Currently, this association table is not needed anymore, as table NG_ENERGYDEMAND has a field containing the foreign key to table NG_CITYOBJECT - and the Importer/Exporter correctly uses it.

I think this table can be excluded from the install script.

**Comment by clausnagel** [comment]
Thanks @gioagu. The 3DCityDB mapping is automatically derived from the XML Schema of the [KIT EnergyADE 1.0 profile](https://github.com/citygml4j/energy-ade-citygml4j/blob/master/resources/ade-xjc/EnergyADE.xsd). The change would have to be made in this schema but the schema is not under our control. 

I am not an expert of the EnergyADE but I guess this table is meant for having a bi-directional mapping between city objects and energy demands. The importer only seems to populate one direction though, that's true.

**Comment by gioagu** [comment]
Hello,

after some reasoning, I think the explanation is as follows and I add it here only for documentation:

- The "demands" property from ADE cityobject to EnergyDemand is mapped to the NG_ENERGY_DEMAND table, column "cityobject_demands_id". This is the most common case, when a cityobject has one or many children EnergyDemand object(s).  

- The ïsDemandedBy"is mapped then to the association table NG_ENERGYDEM_TO_CITYOBJEC. And it is used to map for example when a EnergyDemand is shared by multiple cityobjects. I have never seen it used, personally, and it is when I can imagine this "extra table "to be used.

So, ideally, these two cases could be manually mapped to one single association table, but as a result of the automatic mapping (an its underlying rules) it is now clear to me how it works. In conclusion, it is not a bug.

On a side note: in the Energy ADE 2.0 (currently WIP) we have decided to drop this "isDemandedBy" property. 🙂
